help_table = {
	{ "GRL", "GENERAL INFO", "- This mod can easily ruin the game if used carelessly - you were warned. @ - Any window can be dragged via the top bar. @ - Any window can be closed via the most right top button. @ - Any window can be minimized via the second most right top button. @ - Any entity can be captured at any time via the selected button scheme. @ - You MUST check mod settings for additional options. @", },
	-- { "TBR", "TASKBAR", "- Prospero2000 Logo on the most left functions as the main button. LMB it to open the main window and RMB it to close all the windows. / - Every currently present window is represented as it's own named icon. LMB it to change the minimized status and RMB it to close the window. / - Some windows have parents: when the parent it closed/minimized via the taskbar, so does the child. / - This mod was built upon the Dimensional Structure - a group of independent workspaces. Those may be switched via the arrow keys on the left of the help button. /", },
	-- { "MNW", "MAIN WINDOW", "- This window controls general mod behaviour and functions as a hub to all its functionality. / - 1-3 buttons execute the custom scripts that are located at mods/p2k/data/p2k_custom. You can manually fill them with your own code or just automatically overwrite with the prewritten extension (is not included). / - WSE button targets the World State Entity. / - PSE button targets the Player State Entity. / - SLF button targets the player. / - BTN changes the capture button scheme. / - END button controls the way in which inputable values are displayed: from the start or from the end. / - ZLV button changes the core z-level of the GUI (height is inverted). / - TSF button displays the gizmo that controls the transform component of any entity. The upper and the right ones change the position, the lower and the left ones change the scale and the central point enables full 2D movement. RMB the button to open just raw transform values. / - ESC controls the entity radar that shows every entity on the screen. / - TSK is not implemented yet but is supposed to be a better version of the taskbar. / - FLG opens flag editing window. / - KBD opens the virtual keyboard. / - MIN minimizes every window except the main one. /", },
	-- { "KBD", "KEYBOARD", "- This window allows you to enter custom text and number values. / - You need to have an active input field to use the keyboard. / - LMB the most left bottom button to Shift. / - RMB the backspace to clear the entire line. /", },
	-- { "TFW", "TRANSFORMER", "- This window controls the transform component of the captured entity. / - Note: changing the scale of the physical objects tends to cause bugs. / - X changes the x-pos. / - Y changes the y-pos. / - R changes the rotation in degrees. / - W changes the x-scale. / - H changes the y-scale. /", },
	-- { "FGW", "FLAG WINDOW", "- This window displays all the RunFlags. / - The button on the right of the flag deletes it. / - PRS button grants access to the PersistentFlags menu. Question mark button will check whether is the value inputed present as a flag or not. The most right button will delete any flag that matches the inputed value. Confirm the input to add a flag. / - ADD button adds the RunFlag. Most right button will clear the field. Confirm the input to submit a new flag. /", },
	-- { "ETW", "ENTITY WINDOW", "- This window displays all of the entity's components. / - LMB any component name to open the Component menu. RMB any component name to enable/disable it. Button on the right will delete the component. / - TRK button captures the entity of this window. / - TGS button grants access to the Tags menu. / - NME button controls the entity's name. Button on the right will clear the field. Confirm your input to set the name. / - CLD button grants access to the Children menu. / - ADD button adds new components to the entity. Button on the right will clear the field. Confirm the input to add the component with the entered name. / - For advanced component editing tutorial check tools_modding folder in the root game directory. /", },
	-- { "CDW", "CHILD WINDOW", "- This window displays all of the entity's children. / - LMB any child to open it in the Entity menu. / - Second most right button unchilds the target. / - Most right button deletes it. / - CLR unchilds all the children. / - DLT deletes all the children. / - ADD adds the currently captured entity to the window-entity. /", },
	-- { "TGW", "TAG WINDOW", "- This window displays all of the entity's tags. / - Button on the right deletes any tag. / - CLR deletes all the tags. / - ADD adds new tag. Button on the right clears the field. Confirm the input to add the tag. /", },
	-- { "CPW", "COMP WINDOW", "- This window displays all of the component's/object's fields. / - LMB any value to edit it. / - ENL button enables/disables the component. / - TGS button edits the tags of the component. Question mark will check whether is the value inputed is present as a tag or not. The most right button will delete the tag that matches the inputed value. Confirm the input to add a tag. / - [EDIT] field grants access to the Object/Table/Vector menu that has the similar functionality. /", },
}